services:
  postgres:
    image: postgres:16
    container_name: plaid-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: PlaidProject
    volumes:
      - ./pgdata:/var/lib/postgresql/data
